version: '3.8'
services:
  api:
    container_name: nestjs
    image: nestjs-dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER_NAME: ${DB_USER_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DATABASE: ${DATABASE}
      MAX_CONNECTIONS: ${MAX_CONNECTIONS}
      MAX_SEATS: ${MAX_SEATS}
      VALID_TOKEN_EXPIRATION_TIME: ${VALID_TOKEN_EXPIRATION_TIME}
      SEAT_HOLD_EXPIRATION_TIME: ${SEAT_HOLD_EXPIRATION_TIME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - ticketing-net
    command: pnpm run start

  database:
    container_name: mariadb
    image: mariadb:10.6
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
    networks:
      - ticketing-net
    ports:
      - "3306:3306"

  redis:
    container_name: redis
    image: redis:7.0.0
    restart: unless-stopped
    command: redis-server --notify-keyspace-events Ex
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - ticketing-net
    volumes:
      - redis-data:/data
    
networks:
  ticketing-net:
    driver: bridge

volumes:
  mariadb-data:
    driver: local
  redis-data:
    driver: local
