version: '3.8'
services:
  api:
    container_name: nestjs
    image: nestjs-dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - ticketing-net
    command: pnpm run start

  db:
    container_name: mariadb
    image: mariadb:10.6
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
    networks:
      - ticketing-net
    ports:
      - "3306:3306"

networks:
  ticketing-net:
    driver: bridge

volumes:
  mariadb-data:
    driver: local
