name: 'Close PR on failure'
description: 'Automatically closes PR if the job fails'
inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Close PR
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          github.rest.pulls.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            state: 'closed'
          })
