name: 'Set Environment Variables'
description: 'Set common environment variables for the workflow'
runs:
    using: 'composite'
    steps:
        - name: Set Environment Variables
        run: |
            echo "DB_TYPE=${{ secrets.DB_TYPE }}" >> $GITHUB_ENV
            echo "DB_HOST=localhost" >> $GITHUB_ENV
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
            echo "DB_USER_NAME=${{ secrets.DB_USER_NAME }}" >> $GITHUB_ENV
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
            echo "DATABASE=${{ secrets.DATABASE }}" >> $GITHUB_ENV
            echo "MAX_CONNECTIONS=${{ secrets.MAX_CONNECTIONS }}" >> $GITHUB_ENV
            echo "MAX_SEATS=${{ secrets.MAX_SEATS }}" >> $GITHUB_ENV
            echo "SEAT_HOLD_EXPIRATION_TIME=${{ secrets.SEAT_HOLD_EXPIRATION_TIME }}" >> $GITHUB_ENV
            echo "VALID_TOKEN_EXPIRATION_TIME=${{ secrets.VALID_TOKEN_EXPIRATION_TIME }}" >> $GITHUB_ENV
            echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> $GITHUB_ENV
        shell: bash
