name: CI/CD Pipeline

on:
  push:
    branches: [ master, develop, release, feature/*, hotfix/* ]
  pull_request:
    branches: [ develop, release ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'
    - name: Install Dependencies
      run: npm install
    - name: Run Tests
      run: npm test

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release' || github.ref == 'refs/heads/hotfix/*'
    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and Push Docker images
      run: |
        docker build -t goodmirow/ticketing:${{ github.sha }} .
        docker push goodmirow/ticketing:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: Manual Deployment Steps
      run: |
        echo "Manual deployment steps are required to deploy to production."
        echo "This can involve a manual trigger from within a deployment tool or additional approvals."
